# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo apt-get update && sudo apt-get install -y openssl libssl-dev uuid uuid-dev libldap2-dev
  displayName: Install Libraries

- script: sudo apt-get install -y gcc-8 g++-8
  displayName: Install G++ v8

- task: CMake@1
  inputs:
    workingDirectory: 'cmake-build-debug'
    cmakeArgs: "-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-8 -DCMAKE_C_COMPILER=gcc-8 .."
  displayName: 'CMake Debug Init'

- task: CMake@1
  inputs:
   workingDirectory: 'cmake-build-debug'
   cmakeArgs: "--build . -- -j 4"
  displayName: 'CMake Build Debug'
